### ISSUE TITLE
Wallets were deregistered but coldkey and hotkey still registered to UID. Not recovering. 

### ISSUE THREAD

**Issue by kellnerganoosh** [RusticLuftig/data-universe#197]
Registered UID 216 on 2/20/24. Needed to troubleshoot miner and had to reset paths to coldkey and hotkey. Miner and UID 216 have been live on taostats during this time. Rebooted and fixed miner today. Restarted pm2 mining process and received error (image attached.) Netuid 13 is requesting additional registration even though miner is still registered and in immunity period. 

![Screenshot 2024-02-22 162536](https://github.com/RusticLuftig/data-universe/assets/25893130/83490ea2-9170-460c-819a-ba9594590872)

**Comment by Sid-Data-Universe** [comment]
As discussed you were out of your 30 hour immunity period and got deregged because your miner was down and incentive dropped too low.
